### ISSUE TITLE
Refactor to object-oriented architecture

### ISSUE THREAD

**Issue by nianeyna** [nianeyna/ao3downloader#11]
This is a big task but it should go a long way toward making future development easier. The functional programming approach has its charms but I'm starting to run into its limits - the parameter list for download_recursive is just getting silly, for example.

**Comment by JediMaster25** [comment]
https://github.com/ArmindoFlores/ao3_api

**Comment by nianeyna** [comment]
@JediMaster25 I'm aware of that project - I'm not sure what you intend to communicate by linking it here.

**Comment by JediMaster25** [comment]
Just that it's object oriented and it might help with refactoring this one.

**Comment by nianeyna** [comment]
This issue is stale enough that I'm just going to close it
