### ISSUE TITLE
The PY file cannot run in the Python 3.11 environment.

### ISSUE THREAD

**Issue by MacyNNN** [nianeyna/ao3downloader#181]
I download the python311, and run it to make sure it works. But the PY file is not running properly, and I don't know what else to do.
![aaa](https://github.com/user-attachments/assets/29d30d16-75c3-47c8-98a7-cefb158b533a)
![bbb](https://github.com/user-attachments/assets/868989c1-13b0-4812-bdf2-b0e36acc4902)

**Comment by nianeyna** [comment]
Delete the venv folder, then ignore the .py file and just double-click on ao3downloader.cmd

**Comment by MacyNNN** [comment]
It woks!! I am excited, Thank you for your patient guidance. May I ask one last question, how can I make sure the downloaded file name does not contain the ID?

![ccc](https://github.com/user-attachments/assets/33fd86f9-b475-48e5-bb29-2980b2afa829)

**Comment by nianeyna** [comment]
Open the file named settings.ini, it has instructions for changing the file name pattern

**Comment by MacyNNN** [comment]
I think I completely understand now. Through the combinations of the items in the curly braces, I can customize the file name. Thank you again.
![ddd](https://github.com/user-attachments/assets/6d091bff-e7cc-4d13-adde-d1469b3ffcf0)

**Comment by nianeyna** [comment]
Yes, that's correct. Glad you got it figured out!
