### ISSUE TITLE
How to change the name and path of  downloads folder ？

### ISSUE THREAD

**Issue by MacyNNN** [nianeyna/ao3downloader#182]
I'm sorry to bother you again. I don't want [downloads] folder to be stored in this drive. I want to change its  path and also rename it. What should I do?
![aaa](https://github.com/user-attachments/assets/438abbd1-3697-4e17-9711-77b185275a54)

**Comment by nianeyna** [comment]
Currently I don't support custom download locations, though it is a planned feature. You can track #139 if you want to be notified when it is implemented. In the meantime, if you need to download to a different drive, you can just move the entire script folder to that drive.
