### ISSUE TITLE
Unable To Download Individual Fics From Collections

### ISSUE THREAD

**Issue by moon75phase** [nianeyna/ao3downloader#43]
Hello,nineyna! First and foremost, thank you so much for creating this wonderful program. I have 0 experience in programming and I really appreciate your instructions and this program in general. ( I sent an ask previously if this question is familiar to you.)

I have run into an issue while using it. I can't download individual stories from collections for example Big Bangs. If I include stories in a series, they are able to be downloaded, however the individual fics do not show up in the downloads folder.

I have tried deleting the settings, re-downloading the program itself. and I tried to see if the files were hidden but still nothing. I checked for this issue in several separate collections as well as tried to see if maybe my filters affected the download but the result is the same. 

I have checked the logs and there is only the link of the collection listed but then no stories listed as being downloaded if I don't select to download from a series. 

I don't have this issue if I am downloading from my favorites, from a creators page or from a works tag, just the collections.

I do not know if other people also ran into this issue or if it is just me. I understand if you do not have the time or if it is not possible to fix this issue but I wanted to bring this to your attention.

Thank you so much for making this awesome program! Me and my library are very grateful to you.

**Comment by nianeyna** [comment]
Hi! Thanks so much for reporting this issue. Can you provide a link to a collection that you tried to download where the problem occurred? This will help me to reproduce the issue on my own computer as close as possible to what you're experiencing.

**Comment by nianeyna** [comment]
This is now fixed. The problem was that works linked from a collection page contain the collection name in the link, which didn't match the pattern I was using to identify work links. I've now updated that logic to properly recognize work links with collection prefixes. Thank you again!
