### ISSUE TITLE
Downloaded New Versions of Python and Downloader Now Have a NoModuleFoundError: no module named "requests"

### ISSUE THREAD

**Issue by readingfan** [nianeyna/ao3downloader#64]
Hello,

Thank you for making the the AO3 downloader. I have an issue. I decided to download the newest versions of the downloader and python but now have a NoModuleFound: No module named "requests" error. I think I downloaded everything correctly but I don't know what to do now.

Thank you for reading.

![image](https://user-images.githubusercontent.com/120782639/208238462-ee61ae63-286e-4d01-825a-655959f0ed42.png)

**Comment by readingfan** [comment]
Hello, I was able to fix the issue myself by inputting a command to install requests. I searched for the error online and found a site that said to use "pip3 install requests" which worked for me.

Thank you!

**Comment by nianeyna** [comment]
Glad you got it to work! As a reminder, if you have similar problems in the future, make sure to check the readme to make sure you are using a supported version of python (the very latest version doesn't always work with ao3downloader, unfortunately) as well as following all the steps in the Troubleshooting section to rule out common problems.
