### ISSUE TITLE
The Downloader won't work for some reason.

### ISSUE THREAD

**Issue by instaloadererror** [nianeyna/ao3downloader#76]
I was following the instructions but it didn't work. I already have Python 3.10 as far as I know. I've included a screenshot of the folder where it is. When I try to do the windows: double-click on "ao3downloader.cmd" step it gives me the error in the second screenshot.
![Untitled](https://user-images.githubusercontent.com/67607076/228432448-b3e4cccd-27f2-4b22-b8b6-8b92967a4c29.png)
![Untitle2d](https://user-images.githubusercontent.com/67607076/228432515-6b0506de-2346-47ce-a6fd-9736aa70ce76.png)

**Comment by nianeyna** [comment]
Have you done all of the troubleshooting steps in the readme? If you haven't, please do; if you have, please tell me what the results were

**Comment by instaloadererror** [comment]
> Have you done all of the troubleshooting steps in the readme? If you haven't, please do; if you have, please tell me what the results were

Thank you. I feel very stupid I did not understand the venv thing, but it worked when I tried that again. 

Is there any way to alter what the file name will be on download? Preferably I'd like to be able to see kudos and main fandom.

Also, will it matter if I move the downloaded files afterwards to sort them? Or alternatively is there an option to choose where they download to each time I input a link or does it only allow downloading into ao3downloader-main\downloads?

**Comment by nianeyna** [comment]
Glad you got it working! It is not currently possible to configure the file naming scheme, but that is a planned feature - you can track issue #72 to get notified when it is implemented. I had not considered including number of kudos as an option for that, though. I will think about it. Definitely fandom will be an option though.

You can't download directly to a different folder, but it's fine to move the files to wherever. I assume most people move them after a download - I definitely do haha. (There is some optimization around avoiding repeat downloads that will be lost if you move or rename the fic files, but it's not that important. Especially since in many cases you *want* to download the same fic again)

**Comment by instaloadererror** [comment]
> Glad you got it working! It is not currently possible to configure the file naming scheme, but that is a planned feature - you can track issue #72 to get notified when it is implemented. I had not considered including number of kudos as an option for that, though. I will think about it. Definitely fandom will be an option though.
> 
> You can't download directly to a different folder, but it's fine to move the files to wherever. I assume most people move them after a download - I definitely do haha. (There is some optimization around avoiding repeat downloads that will be lost if you move or rename the fic files, but it's not that important. Especially since in many cases you _want_ to download the same fic again)

I'm having an issue and I'm hoping you might be able to help. I'm trying to download Harry Potter fics with the Fleur Delacour/Hermione Grange relationship tag. The first time I tried this the downloader downloaded three stories and then stopped so I closed it and retried. The second time I got an error and it didn't work, it looks like it has to do with logging in (I've included a screenshot). The third time I deleted the venv folder again and after it did all the setting up again it seems to be working (it's currently downloading). Do you know what the issue was in either the first or second time?

![hermfleur1](https://user-images.githubusercontent.com/67607076/229638991-5cf4c25f-1436-4468-9b1b-3966395f74ed.png)

**Comment by nianeyna** [comment]
Could be that you ran into the login rate limit, though I would have expected it to handle that more gracefully. Could also be just an internet connectivity wobble. If it happens again try checking out the interactive log file (menu option "v")
