### ISSUE TITLE
Update Folder Doesn't Work

### ISSUE THREAD

**Issue by verotheelf** [nianeyna/ao3downloader#77]
Issue occurs while using: 'download latest version of incomplete fics'

The no option for 'check the same folder as last time' does not work. Doesn't prompt for a new folder and still utilizes the one originally saved in settings.json.

Problem seems to be in update_folder() in shared.py. The same code is used for the initial folder save and updating, but this relies on fileops.setting(). The method only prompts for user input/saves if the setting does not yet exist or does not have a value already attached.

**Comment by nianeyna** [comment]
Thank you for this bug report! I really appreciate the amount of detail you've provided. I will definitely look into this and let you know what I find/when there is a fix.
