### ISSUE TITLE
Ao3 reformatted pdf stats?

### ISSUE THREAD

**Issue by verotheelf** [nianeyna/ao3downloader#79]
When I update incomplete fics from folder, I have the program search through my PDFs, but realized the other day that some of them weren't downloading despite there being a new update. Looked through the pdfs causing issues and it appears the stats are now formatted Published, Updated, Words, Chapters. Because 'Words' is no longer at the end, unless there is no 'Updated' stat, the actual chapter numbers get thrown onto the second line. Since the logic for finding pdf stats assumes they are on the same line as 'Chapters: ', it's now broken.

I also download EPUBs so I tried searching for incomplete fics using that format instead. Seems to still be working, but not sure if any other formats are also affected.

**Comment by nianeyna** [comment]
Yeah... this doesn't suprise me too much, that pdf parsing was always going to be delicate 😭 This one might take me a little bit longer to fix. Pretty sure other formats should be unaffected, the pdfs are just a PITA. Thank you again for reporting these bugs! I really appreciate it
