### ISSUE TITLE
Updated Fic Not Properly Detected

### ISSUE THREAD

**Issue by verotheelf** [nianeyna/ao3downloader#80]
Noticed some inconsistencies in the program's ability to detect updated work, no matter which format I had it check. Found that it was correctly determining the chapter count on both my fic and its counterpart on ao3. 

Isolated the problem to try_download() in ao3.py. When it compares currentchapters to chapters, both values are still strings so in my case, 10<=9 was coming back True. Wrapping the values in an int function during comparison seems to resolve the issue.

**Comment by nianeyna** [comment]
For what feels like the millionth time, thank you so much for your perspicacity. I feel quite sheepish for not catching this one. I'm regression testing the fix now - should be pushed soon! Also - don't feel obligated by any means, but feel free to make pull requests for these sorts of things if you like. I'm not *too* precious about accepting help!
