### ISSUE TITLE
ModuleNotFound: No Module named 'bs4' Error

### ISSUE THREAD

**Issue by readingfan** [nianeyna/ao3downloader#81]
Hello, ninaneya

I hope everything is going well for you. Thank you as always for your hard work. I downloaded the most current version of the downloaded and ran into this issue:

ModuleNotFound: No Module named 'bs4' Error

I tried to research it myself and found out it has something to do with a thing called Beautiful Soup but could not install it by opening python and inputting the command that was listed in it. One of the advice forums said to open a virtualenv? Is that the python command screen?

Any help would be greatly appreciated.

**Update**: I was able to install 'bs4' after spending time troubleshooting it. via "pip install"? But after doing that, the program said it didn't have several other modules: ebook, mobi and something else I think as well?

For reference my python program is 3.10 and I was trying to install the most recent version of the program..

Thank you for creating this program! I really appreciate it.

**Comment by nianeyna** [comment]
@readingfan did you figure this out?

**Comment by readingfan** [comment]
I did end up figuring it out. I had to update several things for it in the end besides the "bs4" thing. At least 4 or 5 different items. After updating the "bs4" I ended up doing the same for the modules the program was saying were bad.

Thank you for your time.
