### ISSUE TITLE
Creating a link list with metadata is throwing an error. 

### ISSUE THREAD

**Issue by instaloadererror** [nianeyna/ao3downloader#84]
I tried twice and got the same error at the same point. 
![ao3downloader error](https://user-images.githubusercontent.com/67607076/236708836-ebcb3864-3eb4-467f-8265-ec06a7edffb7.png)

If you want the specific link I used without having to type it out: https://archiveofourown.org/works?commit=Sort+and+Filter&work_search%5Bsort_column%5D=kudos_count&work_search%5Bother_tag_names%5D=&work_search%5Bexcluded_tag_names%5D=&work_search%5Bcrossover%5D=&work_search%5Bcomplete%5D=&work_search%5Bwords_from%5D=&work_search%5Bwords_to%5D=&work_search%5Bdate_from%5D=&work_search%5Bdate_to%5D=&work_search%5Bquery%5D=&work_search%5Blanguage_id%5D=&tag_id=Wednesday+%28TV+2022%29

**Comment by nianeyna** [comment]
Is there an error message recorded in the log file?

**Comment by instaloadererror** [comment]
> Is there an error message recorded in the log file?

Would I find that by using the "v" option? I don't know what to do with a jsonl file. I selected the "v" option but it hasn't done anything yet. Does it normally take a while to convert?

**Comment by nianeyna** [comment]
Yeah, it can take a hot minute. If it's been thinking the entire 30 minutes since you left this comment your log file might just be too powerful for it though, lol. If that's the case feel free to email me the raw .jsonl and I'll take a look.

**Comment by instaloadererror** [comment]
> Yeah, it can take a hot minute. If it's been thinking the entire 30 minutes since you left this comment your log file might just be too powerful for it though, lol. If that's the case feel free to email me the raw .jsonl and I'll take a look.

I've emailed it to you. It did eventually finish, but I can't open the .html in Chrome or Firefox all the way. It's too big.

**Comment by nianeyna** [comment]
Do you have a vpn?

**Comment by instaloadererror** [comment]
> Do you have a vpn?

I do not.

**Comment by nianeyna** [comment]
Well, that rules out that easy explanation. I might have to investigate this more later - it's getting late.

**Comment by nianeyna** [comment]
@verotheelf oh, fantastic, thank you! That is immeasurably helpful - you're a treasure

**Comment by nianeyna** [comment]
@instaloadererror I have tested the page you had problems on with the latest code, and this should now be fixed. @verotheelf thank you so much again for your help on this!
